name: MultiVersionPlugin
version: 1.0.0
main: Luthfi\MultiVersion\Main
api: 5.0.0
author: Luthfi
description: MultiVersion support for PocketMine-MP
commands:
  mv:
    description: Test MultiVersion handling
    usage: /mv
    permission: multiversion.use
permissions:
  multiversion.use:
    description: Allows the player to use the MultiVersion command
    default: true
